---
# Set various defaults which will update the relevant plist files
software_app_defaults:

  # ---------------------------------------------------------------------------
  # General Software
  # ---------------------------------------------------------------------------

  # f.lux
  - domain: org.herf.Flux
    values:
      moveToApplicationsFolderAlertSuppress: true
      lateColorTemp: 2400.0
      nightColorTemp: 2800.0
      dayColorTemp: 3200.0
      locationTextField: Melbourne, Australia
      locationType: L
      location: '-37.814107,144.963280'
      wakeTime: 480

  # Microsoft Office
  - domain: ~/Library/Group Containers/UBF8T346G9.Office/com.microsoft.officeprefs.plist
    values:
      kCUIThemePreferencesThemeKeyPath: 0

  - domain: com.microsoft.Excel
    container: com.microsoft.Excel
    values:
      kSubUIAppCompletedFirstRunSetup1507: true

  - domain: com.microsoft.Word
    container: com.microsoft.Word
    values:
      kSubUIAppCompletedFirstRunSetup1507: true

  - domain: com.microsoft.Powerpoint
    container: com.microsoft.Powerpoint
    values:
      kSubUIAppCompletedFirstRunSetup1507: true

  - domain: com.microsoft.onenote.mac
    container: com.microsoft.onenote.mac
    values:
      kSubUIAppCompletedFirstRunSetup1507: true

  - domain: com.microsoft.Outlook
    container: com.microsoft.Outlook
    values:
      kSubUIAppCompletedFirstRunSetup1507: true

  # MPlayerX
  - domain: org.niltsh.MPlayerX
    values:
      SUSendProfileInfo: false
      SUEnableAutomaticChecks: true
      # General / Keep window on top / Never
      OnTopMode: 0


  # Skype
  - domain: com.skype.skype
    values:
      # Preferences / Contacts / Untick Show Mac Contacts
      ShowAddressBookContacts: false
      # View / as List
      ContactListViewMode: 1


  # Transmission
  - domain: org.m0k.transmission
    values:
      # Transfers / Trash original torrent files
      DeleteOriginalTorrent: true
      # Hide the legal disclaimer
      WarningLegal: false

  # Twitter
  - domain: com.twitter.twitter-mac
    container: com.twitter.twitter-mac
    values:
      # General / Font size / 16 pt
      FontSize1: 16
      # General / Theme / Dark Theme
      TMSelectedThemeIdentifier: com.twitter.twitter.themeIdentifiers.darkTheme

